fix clang + glibc `std::simd` issue (#545)
The modulo operator for std::simd in glibc 12 is implemented on such a
way that it compiles only with gcc, therefore a workaround is required.

error:

```
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/experimental/bits/simd_x86.h:1492:51: error:
explicit qualification required to use member '_S_divides' from dependent base class 1492 |           return
_Base::_S_minus(__x, _S_multiplies(__y, _S_divides(__x, __y)));
```