example: fix scan with CUDA
fix comiler issue when using CUB

```
include/cuda/std/detail/libcxx/include/__functional/operations.h(367): error: name followed by "::" must be a class or namespace name
          noexcept(noexcept(::cuda::std::__4::forward<_T1>(__t) == ::cuda::std::__4::forward<_T2>(__u)))
```
and
```
include/cccl/cub/warp/warp_scan.cuh(176): error: "cuda" is ambiguous
2805
      IS_INTEGER = cuda::std::is_integral_v<T>
```

The error happen because we used `using namespace alpaka;` in the clobal
cpp which collided with cub internal calls.